name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{secrets.HOST_DNS}}
            USER_NAME: ${{secrets.USERNAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Deploy Commands here

              cd ~/storynoi
              pm2 delete storynoi
              pm2 save --force
              git checkout master
              git pull origin master
              npm i
              npm run start
              pm2 start npm --name "storynoi" -- start
              '
