name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 

      - name: Print
        run: | 
          echo ${{ secrets.EC2_SSH_KEY }} >> secrets.txt
          cat secrets.txt
      
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{secrets.HOST_DNS}}
            USER_NAME: ${{secrets.USERNAME}}
      
        run: |
          echo $PRIVATE_KEY >> secrets.txt
          echo $HOSTNAME >> secrets.txt
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          cat private_key
          echo ${{ secrets.EC2_SSH_KEY }}
          sudo ssh -i private_key ${USER_NAME}@${HOSTNAME}

              # Deploy Commands here
              . ./export_env.sh
              cd ~/storynoi
              pm2 delete storynoi
              pm2 save
              git checkout main
              git pull origin main
              npm i
              npm run start
              pm2 start npm --name "storynoi" -- start
              '

